// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRsp {
    /// 指令类型
    #[prost(enumeration = "heartbeat_rsp::CmdType", tag = "1")]
    pub cmd_type: i32,
    /// 指令内容
    #[prost(string, tag = "2")]
    pub cmd_content: ::prost::alloc::string::String,
}
/// Nested message and enum types in `HeartbeatRsp`.
pub mod heartbeat_rsp {
    /// 指令类型枚举
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CmdType {
        /// 啥也不干
        Nothing = 0,
        /// 打印日志
        Print = 1,
    }
    impl CmdType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Nothing => "NOTHING",
                Self::Print => "PRINT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NOTHING" => Some(Self::Nothing),
                "PRINT" => Some(Self::Print),
                _ => None,
            }
        }
    }
}
/// 心跳消息请求结构体
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterReq {
    /// agent唯一编号，必填
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    /// agent版本，必填
    #[prost(string, tag = "2")]
    pub agent_version: ::prost::alloc::string::String,
}
/// 心跳消息请求结构体
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRsp {
    /// 认证token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostReq {
    #[prost(message, optional, tag = "1")]
    pub system: ::core::option::Option<SystemInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfo {
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub kernel_version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub os_version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub host_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub cpu_arch: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub kernel_long_version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub total_memory: u64,
    #[prost(uint64, tag = "8")]
    pub total_swap: u64,
    #[prost(message, repeated, tag = "9")]
    pub processes: ::prost::alloc::vec::Vec<Process>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Process {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub exe: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
}
