#!/bin/bash
# Created by zhaogj on 20240528
set -o errexit
set -x

cd "$(dirname "${0}")" || exit
cd ../

# build server
cd server
cargo update
cargo zigbuild -r --target=x86_64-unknown-linux-musl
cd ui_web
npm install
npm run build
cd ../../

# clean server
rm -rf z11n_server.tar.gz
rm -rf z11n_server

# make server dir
mkdir -p z11n_server/bin
mkdir -p z11n_server/config
mkdir -p z11n_server/log
mkdir -p z11n_server/data
mkdir -p z11n_server/html

# copy server file
cp server/target/x86_64-unknown-linux-musl/release/z11n_server z11n_server/bin/
cp script/service z11n_server/bin/
chmod +x z11n_server/bin/*
cp server/z11n_server/config/* z11n_server/config
cp -r server/ui_web/dist/* z11n_server/html

# tar server pkg
tar --disable-copyfile -zcvf z11n_server.tar.gz z11n_server
rm -rf z11n_server
echo "make z11n_server.tar.gz success"

# build client
cd client
cargo update
cargo zigbuild -r --target=x86_64-unknown-linux-musl
cd ../

# clean client
rm -rf z11n_agent.tar.gz
rm -rf z11n_agent

# make client dir
mkdir -p z11n_agent/bin
mkdir -p z11n_agent/config
mkdir -p z11n_agent/log

# copy file
cp client/target/x86_64-unknown-linux-musl/release/z11n_agent z11n_agent/bin/
cp script/service z11n_agent/bin/
chmod +x z11n_agent/bin/*
cp client/z11n_agent/config/* z11n_agent/config

# tar z11n_agent pkg
tar --disable-copyfile -zcvf z11n_agent.tar.gz z11n_agent
rm -rf z11n_agent
echo "make z11n_agent.tar.gz success"

# z11n_llm_task_consumer
mkdir -p z11n_llm_task_consumer/bin
mkdir -p z11n_llm_task_consumer/config
mkdir -p z11n_llm_task_consumer/log

cp client/target/x86_64-unknown-linux-musl/release/z11n_llm_task_consumer z11n_llm_task_consumer/bin/
cp script/service z11n_llm_task_consumer/bin/
chmod +x z11n_llm_task_consumer/bin/*
cp client/z11n_agent/config/* z11n_llm_task_consumer/config

# tar z11n_llm_task_consumer pkg
tar --disable-copyfile -zcvf z11n_llm_task_consumer.tar.gz z11n_llm_task_consumer
rm -rf z11n_llm_task_consumer
echo "make z11n_llm_task_consumer.tar.gz success"

# z11n_llm_task_producer
mkdir -p z11n_llm_task_producer/bin
mkdir -p z11n_llm_task_producer/config
mkdir -p z11n_llm_task_producer/log

cp client/target/x86_64-unknown-linux-musl/release/z11n_llm_task_producer z11n_llm_task_producer/bin/
cp script/service z11n_llm_task_producer/bin/
chmod +x z11n_llm_task_producer/bin/*
cp client/z11n_agent/config/* z11n_llm_task_producer/config

# tar z11n_llm_task_producer pkg
tar --disable-copyfile -zcvf z11n_llm_task_producer.tar.gz z11n_llm_task_producer
rm -rf z11n_llm_task_producer
echo "make z11n_llm_task_producer.tar.gz success"
