refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%m-%d %H:%M:%S.%6f)} {l} {t}[{L}] {m}{n}"

  file:
    kind: rolling_file
    path: "log/service.log"
    append: true
    encoder:
      pattern: "{d(%m-%d %H:%M:%S.%6f)} {l} {t}[{L}] {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: "log/service.log.{}"
        base: 1
        count: 9

root:
  level: info
  appenders:
    - file
    # - stdout

loggers:
  sqlx::query:
    level: warn
  sea_orm_migration::migrator:
    level: trace
  sqlx::postgres::notice:
    level: trace
