//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::tbl_agent::Entity as TblAgent;
pub use super::tbl_auth_role::Entity as TblAuthRole;
pub use super::tbl_auth_user::Entity as TblAuthUser;
pub use super::tbl_auth_user_role::Entity as TblAuthUserRole;
pub use super::tbl_host::Entity as TblHost;
pub use super::tbl_llm_task::Entity as TblLlmTask;
pub use super::tbl_system_config::Entity as TblSystemConfig;
