//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_auth_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub apis: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_auth_user_role::Entity")]
    TblAuthUserRole,
}

impl Related<super::tbl_auth_user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAuthUserRole.def()
    }
}

impl Related<super::tbl_auth_user::Entity> for Entity {
    fn to() -> RelationDef {
        super::tbl_auth_user_role::Relation::TblAuthUser.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tbl_auth_user_role::Relation::TblAuthRole.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
