//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_auth_user_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_auth_role::Entity",
        from = "Column::RoleId",
        to = "super::tbl_auth_role::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAuthRole,
    #[sea_orm(
        belongs_to = "super::tbl_auth_user::Entity",
        from = "Column::UserId",
        to = "super::tbl_auth_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAuthUser,
}

impl Related<super::tbl_auth_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAuthRole.def()
    }
}

impl Related<super::tbl_auth_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAuthUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
