//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_llm_task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub req_agent_id: String,
    pub model: String,
    pub prompt: String,
    pub req_content: String,
    pub req_push_at: DateTime,
    pub req_pull_at: Option<DateTime>,
    pub rsp_agent_id: Option<String>,
    pub rsp_content: Option<String>,
    pub rsp_push_at: Option<DateTime>,
    pub rsp_pull_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
