[package]
edition = "2024"
name = "entity"
version = "0.1.0"

[dependencies]
sea-orm = {version = "1.1.14", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros"]}
serde = {version = "1.0.219", features = ["derive"]}
